DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS PRICES;

CREATE TABLE STORE (

   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL
);

CREATE TABLE PRICES (

    id INT AUTO_INCREMENT PRIMARY KEY,
    brand_id INT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    price_list INT NOT NULL,
    product_id INT NOT NULL,
    priority INT NOT NULL,
    price NUMERIC NOT NULL,
    curr CHAR(3) NOT NULL,
    FOREIGN KEY (brand_id) REFERENCES Store(id)
);